# MLS file manager flavor.
[mgr]
marker_copied = { fg = "#96b970", bg = "#96b970" }
marker_cut = { fg = "#df7e90", bg = "#df7e90" }
marker_marked = { fg = "#b69de5", bg = "#b69de5" }
marker_selected = { fg = "#c9a470", bg = "#c9a470" }
cwd = { fg = "#c9a470" }
find_keyword = { fg = "#e49b70", bg = "#1a1a1a" }
find_position = {}
count_copied = { fg = "#0e0e0e", bg = "#96b970" }
count_cut = { fg = "#0e0e0e", bg = "#df7e90" }
count_selected = { fg = "#0e0e0e", bg = "#c9a470" }
border_symbol = "│"
border_style = { fg = "#c8c8c8" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { reversed = true }

[tabs]
active = { fg = "#0e0e0e", bg = "#82a0e0" }
inactive = { fg = "#82a0e0", bg = "#1a1a1a" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#0e0e0e", bg = "#82a0e0" }
normal_alt = { fg = "#82a0e0", bg = "#1a1a1a" }
select_main = { fg = "#0e0e0e", bg = "#b69de5" }
select_alt = { fg = "#b69de5", bg = "#1a1a1a" }
unset_main = { fg = "#0e0e0e", bg = "#c9a470" }
unset_alt = { fg = "#c9a470", bg = "#1a1a1a" }

[status]
overall = { fg = "#c8c8c8", bg = "#0e0e0e" }
progress_label = { fg = "#82a0e0", bold = true }
progress_normal = { fg = "#1a1a1a", bg = "#82a0e0" }
progress_error = { fg = "#1a1a1a", bg = "#df7e90" }
perm_type = { fg = "#96b970" }
perm_read = { fg = "#c9a470" }
perm_write = { fg = "#df7e90" }
perm_exec = { fg = "#79c5b9" }
perm_sep = { fg = "#b69de5" }

[pick]
border = { fg = "#82a0e0" }
active = { fg = "#b69de5", bold = true }
inactive = {}

[input]
border = { fg = "#82a0e0" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#82a0e0" }
active = { reversed = true }
inactive = {}

[which]
cols = 2
separator = " - "
separator_style = { fg = "#585d76" }
mask = { bg = "#0e0e0e" }
rest = { fg = "#585d76" }
cand = { fg = "#82a0e0" }
desc = { fg = "#44484e" }

[help]
on = { fg = "#96b970" }
run = { fg = "#b69de5" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#0e0e0e", bg = "#c8c8c8" }

[notify]
title_info = { fg = "#96b970" }
title_warn = { fg = "#c9a470" }
title_error = { fg = "#df7e90" }

[filetype]
rules = [
    { mime = "image/*", fg = "#c9a470" },
    { mime = "{audio,video}/*", fg = "#b69de5" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#df7e90" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#79c5b9" },
    { url = "*", is = "orphan", fg = "#df7e90" },
    { url = "*", is = "exec", fg = "#96b970" },
    { url = "*", fg = "#c8c8c8" },
    { url = "*/", fg = "#82a0e0" },
]
